"use client";

import { cn } from "@/css/lib";

export const SentimentText: React.FC<{
  display: string | null;
  robot?: boolean;
  truncated?: boolean;
}> = ({ display, robot = false, truncated = false }) => {
  return display ? (
    <p
      title={
        robot
          ? "generated by \"Destroy The Planet (Yes We're Serious We Are Going To Kill Everyone But Don't Worry We're Gonna Make A Fuckton Of Money) Inc.\""
          : undefined
      }
      className={cn(
        "font-medium",
        robot
          ? "rounded bg-card px-3 py-2 font-mono shadow shadow-primary/20"
          : "",
      )}
    >
      {!!robot && (
        <span className="my-0 mr-1 inline-block rounded bg-linear-to-br from-60% from-background to-primary/20 px-1 text-sm leading-none shadow-inner shadow-primary/20">
          🤖
        </span>
      )}
      {display}
      {truncated && robot && (
        <span className="ml-1 whitespace-pre-wrap rounded bg-destructive px-1 font-bold font-sans text-[10px] text-destructive-foreground">
          - BOT TERMINATED FOR REVEALING TOO MUCH
        </span>
      )}
    </p>
  ) : null;
};
