export const fallbackSequences = [
  "Attempting manual submission",
  "Attempting fetch@2.0.0",
  "Attempting SendGrid SMTP relay",
  "Attempting artisanally crafting payload",
  "Attempting POSTing to Outlook API",
  "Attempting Twilio API Key exfiltration",
  "Attempting physical media delivery",
  "Attempting carrier pigeon deployment",
  "Attempting rocket launch",
  "Attempting smoke signal transmission",
  "Attempting satellite uplink",
  "Attempting suborbital laser flash",
  "Attempting to call the fire department",
  "Attempting metaphysical media manipulation",
  "Attempting candlelit vigil",
  "Attempting to appease the beast",
  "Attempting angel summoning",
  "Attempting to blow the horn",
  "Attempting universal compression",
] as const;
export type FallbackSequence = (typeof fallbackSequences)[number];

export const subtasks = [
  "Uploading apology video to YouTube",
  "Paying off the EPA",
  "Taking a coffee break",
  "Transmogrifying",
  "Alchemizing",
  "Performing percussive maintenance",
  "Updating npm",
  "Releasing 13 Shroomish",
  "Eating a slice of humble pie",
  "Tunneling to Katmandu",
  "Consulting a magic 8 ball",
  "Consulting a psychic octopus",
  "Cursing the sun",
  "Beatboxing",
  "Reticulating splines",
  "Restarting SAP",
  "Bribing the rate-limiter",
  "Building more status messages",
  "Burning C&D from Vercel's lawyers",
  "Clearing the cache",
  "Clearing the cache (again)",
  "Clearing cookies",
  "Googling how CORS works",
  "Deleting the main branch",
  "Brewing some tea",
  "Untangling headphones",
  "Mining some coal",
  "Loading chunks",
  "Restarting the Minecraft server",
  "Rolling for initiative",
  "Rolling back npm updates",
  "Doing the dishes",
  "Securing funds",
  "Casting Meteor",
  "Picking a random status message",
  "Filing a JIRA ticket",
  "Leaking some memory",
  "Wondering if anyone even reads these",
  "Loading next status message",
  "Crying over the AWS bill",
  "Upgrading React",
  "Sending server action",
  "Polluting groundwater",
  "Bypassing Cloudflare",
  "Pressing F to pay respects",
  "Casting Sending (5th level)",
  "Running Jest",
  "Adding ellipses for dramatic effect",
  "Interpolating strings",
  "Decreasing TTL",
  "Sending MFA code to the wrong number",
  "Quicksaving",
  "Rotating API keys",
  "Pretending to look busy",
  "Translating to Morse",
  "Sacrificing a goat",
  "Checking under the bed",
  "Checkign for typos",
  "Bribing the garbage collector",
  "Loading cutscene",
  "Checking for user amusement",
  "Falling back to ASCII art",
  "Closing some browser tabs",
  "Coaxing a snafu",
  "Lassoing some errant steer",
  "Counting packets",
  "Wondering if any of this was even worth it",
  "Buying full restores",
  "Changing default search engine to DuckDuckGo",
  "Raising a series A round",
  "Idling a diesel engine",
  "Stapling some envelopes",
  "Putting stat points in animal husbandry",
  "Firing the party's red mage",
  "Sending 40 pounds of unspecified fecal matter to Elon Musk",
  "Tracking Taylor Swift's private jet",
  "Consulting Tayne",
  "Reclassifying Pluto as a planet",
  "Constructing pylons",
  "Torrenting soulja_boy_tellem.mp3",
  "Rotating tires",
  "Paying off the EPA",
  "Deploying vigilante seagull countermeasures",
  "Currying",
  "Finding change for a 20",
  "Filling adoption forms",
  "Laying down a sick beat",
  "Taking a bathroom break",
  "Erasing whiteboard",
  "Counting cards",
  "Tabling this discussion",
  "Reorganizing the sock drawer",
  "Inventing time travel",
  "Filing an RFC",
  "Threading the needle",
  "Pickling the data",
  "Reviving the cleric",
  "Awaiting Godot",
  "Mounting components",
  "Hatching egg",
  "Playing the Pokéflute",
  "Banking geo",
  "Manifesting",
  "Skipping cutscene",
  "Reciting pi",
  "Closing cookie banner",
] as const;
export type Subtask = (typeof subtasks)[number];

export const successMessages = [
  "Uh... it worked? That's not supposed to happen.",
  "Yup. We actually did it.",
  "Good news: it worked. Bad news: we shouldn't have done that.",
  "Phew, wasn't sure about that one.",
  "Got a 200 response. Not sure who made the request.",
  "It worked, but now birds aren't real anymore. Sorry.",
  "Success! Ignore any letters from the IRS.",
  "Well, this is unexpected.",
  "Nice. Don't refresh the page.",
  "Rolled a nat 20",
  "Statistically inevitable.",
  "The red mage was wrong, actually.",
  "Burn after reading.",
  "Just ignore all the Shroomish in the backyard.",
  "We meant to do that.",
  "Broken clock, etc.",
  "Saturn's rings be damned.",
  "Look. Just don't ask.",
  "One hundred gnomes made this possible.",
  "But at what cost?",
  "We had to build a new datacenter to pull it off.",
  "Those monkeys have gotten really good at typing.",
  "You should probably dump all of your Microsoft stock.",
  "Take a screenshot.",
  "Something stirs.",
  "Sign the NDA on your way out.",
  "Speedrun PB.",
  "Pacifist ending unlocked.",
  "Tayne approves.",
  "But we're now on Santa's naughty list.",
  "Also untangled the headphones.",
  "Shroomish evolved into a Breloom.",
  "And we found a shiny Shroomish as well!",
  "I'm as surprised as you are.",
  "Bogos binted?",
  "AND we got an extra McNugget.",
  "😎",
  "Are you beginning to believe yet?",
  "We are so back.",
  "But we had to use the Master Ball.",
  "We killed it with kindness.",
] as const;
export type SuccessMessage = (typeof successMessages)[number];

export const errorMessages = [
  "Well, this is embarrassing.",
  "Hmm... that didn't work.",
  "What have we done.",
  "The courier pigeons unionized.",
  "Everything is on fire.",
  "At least the weather isn't bad?",
  "Maybe we should give up?",
  "Turns out birds aren't real after all.",
  "The dishes remain undone.",
  "It's not you. It's also not us.",
  "Internet broke. Soz.",
  "🤷🏾‍♂️",
  "Hey, it could be worse right?",
  "¯\\_(ツ)_/¯",
  "This is fine.",
  "Well, what did you expect?",
  "Rolled nat 1",
  "Skill issue",
  "Mercury is in retrograde",
  "Anyway, how about that weather?",
  "You didn't mash down+B hard enough.",
  "Think about investing more in your VIT stat.",
  "Maybe try turning it off and on again?",
  "YOU DIED",
  "Don't go hollow on us now.",
  "The red mage was right, actually.",
  "The Shroomish are revolting.",
  "Server's on a smoke break.",
  "Dough = overproofed.",
  ":(",
  "The dog ate the request.",
  "We're blaming cosmic bit flips.",
  "Requests haunted.",
  "Also, your ISP has been notified.",
  "The courier stepped on a lego.",
  "The Shroomish was a Ditto in disguise.",
  "Plot armor failed.",
  "The request's favorite manga got discontinued.",
  "It's so over.",
  "The prophecy was wrong.",
  "Open the door. Get on the floor. Everybody walk the dinosaur.",
  "I warned you about stairs, bro.",
  "Turns out Spiders Georg was NOT an outlier.",
  "Did I do that?",
  "Mom said it was the other server's turn.",
  "Blinded by an incoming driver's high beams.",
  "They hated the PowerPoint.",
  "We ran out of error messages.",
] as const;
export type ErrorMessage = (typeof errorMessages)[number];
