export const ordered = [
  "Falling back to manual submission",
  "Polyfilling `fetch@2.0.0`",
  "Creating SendGrid account",
  "Building payload",
  "Testing with yaak",
  "Scraping Twilio APIs",
  "Falling back to physical media",
  "Deploying carrier pigeons",
  "Preparing vigilante seagull countermeasures",
  "Launching rockets",
  "Uploading apology video to YouTube",
  "Falling back to smoke signals",
  "Buying shares in a satellite company",
  "Aiming suborbital lasers",
  "Calling the fire department",
  "Paying off the EPA",
  "Falling back to metaphysical media",
  "Lighting candles in a dark room",
  "Preparing vigil",
  "Appeasing the beast",
  "Summoning angels",
  "Blowing the horn",
  "Falling back to CYA",
  "Checking if the user is still there",
  "Loading spinner",
  "Spinning loader",
] as const;

export const unordered = [
  "Taking a coffee break",
  "Transmogrifying",
  "Alchemizing",
  "Performing percussive maintenance",
  "Updating npm",
  "Releasing 13 Caterpie",
  "Eating a slice of humble pie",
  "Tunneling to Katmandu",
  "Consulting a magic 8 ball",
  "Consulting a psychic octopus",
  "Cursing the sun",
  "Beatboxing",
  "Reticulating splines",
  "Restarting SAP",
  "Bribing the rate-limiter",
  "Building more status messages",
  "Burning C&D from Vercel's lawyers",
  "Clearing the cache",
  "Clearing the cache (again)",
  "Clearing cookies",
  "Googling how CORS works",
  "Deleting the main branch",
  "Brewing some tea",
  "Untangling headphones",
  "Mining some coal",
  "Loading chunks",
  "Restarting the Minecraft server",
  "Rolling for initiative",
  "Rolling back npm updates",
  "Doing the dishes",
  "Securing funds",
  "Casting Meteor",
  "Picking a random status message",
  "Filing a JIRA ticket",
  "Leaking some memory",
  "Wondering if anyone even reads these",
  "Loading next status message",
  "Crying over the AWS bill",
  "Upgrading React",
  "Sending server action",
  "Polluting groundwater",
  "Bypassing Cloudflare",
  "Pressing F to pay respects",
  "Casting Sending (5th level)",
  "Running Jest",
  "Adding ellipses for dramatic effect",
  "Interpolating strings",
  "Decreasing TTL",
  "Sending MFA code to the wrong number",
  "Quicksaving",
  "Rotating API keys",
  "Pretending to look busy",
  "Translating to Morse",
  "Sacrificing a goat",
  "Checking under the bed",
  "Checkign for typos",
  "Bribing the garbage collector",
  "Loading cutscene",
  "Checking for user amusement",
  "Falling back to ASCII art",
  "Closing some browser tabs",
  "Coaxing a snafu",
  "Lassoing some errant steer",
  "Counting packets",
  "Wondering if any of this was even worth it",
  "Buying full restores",
  "Changing default search engine to DuckDuckGo",
  "Raising a series A round",
  "Idling a diesel engine",
  "Stapling some envelopes",
  "Putting stat points in animal husbandry",
  "Firing the party's red mage",
  "Sending 40 pounds of unspecified fecal matter to Elon Musk",
  "Tracking Taylor Swift's private jet",
] as const;
